name: Update Daily.dev-Card

# Step values	20/15 * * * * runs every 15 minutes starting from minute 20 through 59 (minutes 20, 35, and 50).

on:
  schedule: [ { cron: "10 */16 * * *" } ]
  workflow_dispatch:

jobs:
  devcard:
    runs-on: ubuntu-latest

    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.6
        with:
          devcard_id: ${{ secrets.DAILYDEV_CARD_ID }}
          token: ${{ secrets.GH_TOKEN }}
          commit_branch: devcard
          commit_message: "Update `${filename}`"
