name: Update the daily GitHub Metrics

on:
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  update-github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Update GitHub Metrics
        uses: lowlighter/metrics@v3.16
        with:
          # GitHub Personal Token
          token: ${{ secrets.GH_TOKEN }}

          # GitHub Token used to commit metrics
          committer_token: ${{ secrets.GH_TOKEN }}
          # Branch used to commit rendered metrics
          committer_branch: github-metrics
          # Commit message
          committer_message: "Update `${filename}`"

          # GitHub username
          user: mheob
          # Template to use
          template: classic
          # Metrics base content
          base: header, activity, community, repositories, metadata
          # Render display width
          config_display: large # optional, default regular
          # Timezone used
          config_timezone: Europe/Berlin

          # Display achievements
          plugin_achievements: yes
          # Display rank minimal threshold
          #plugin_achievements_threshold: # optional, default is C
          # Display unlocked secrets achievements
          #plugin_achievements_secrets: # optional, default is true
          # Achievements display style
          #plugin_achievements_display: detailed # optional, default is detailed
          # Maximum number of achievements to display
          #plugin_achievements_limit: # optional, default is 0
          # Unlocked achievements to hide
          #plugin_achievements_ignored: # optional, default is
          # Unlocked achievements to display
          #plugin_achievements_only: # optional, default is

          # Display follow-up of repositories issues and pull requests
          plugin_followup: yes
          # Sections to display
          plugin_followup_sections: user # optional, default is repositories
          # Indepth follow-up processing
          plugin_followup_indepth: yes

          # Display most used languages metrics
          plugin_languages: yes # optional
          # Languages to ignore
          #plugin_languages_ignored: inno setup,java,c#,shell # optional, default is
          # Repositories to skip
          #plugin_languages_skipped: # optional, default is
          # Maximum number of languages to display
          #plugin_languages_limit: # optional, default is 8
          # Sections to display
          #plugin_languages_sections: # optional, default is most-used
          # Custom languages colors
          #plugin_languages_colors: # optional, default is github
          # Custom languages names
          #plugin_languages_aliases: # optional, default is
          # Additional details
          plugin_languages_details: percentage #bytes-size, percentage # optional, default is
          # Minimum threshold
          # plugin_languages_threshold: # optional, default is 0%
          # Indepth languages processing (see documentation before enabling)
          plugin_languages_indepth: yes # optional
          # Languages analysis timeout
          #plugin_languages_analysis_timeout: # optional, default is 15
          # Language categories to display
          #plugin_languages_categories: # optional, default is markup, programming
          # Language categories to display (for recently used section)
          #plugin_languages_recent_categories: # optional, default is markup, programming
          # Number of events to load (for recently used section)
          plugin_languages_recent_load: 500 # optional, default is 300
          # Maximum event age (for recently used section)
          plugin_languages_recent_days: 14 # optional, default is 14

          # Display lines of code metrics
          plugin_lines: yes

          # Display notable contributions in organizations
          plugin_notable: yes
          # Query filter
          plugin_notable_filter: stars:>4 # optional, default is
          # Filter by repository host account type
          plugin_notable_from: all # optional, default is organization
          # Also display repository name
          plugin_notable_repositories: yes # optional
          # Indepth notable contributions processing
          plugin_notable_indepth: yes # optional

          # Display repositories traffic metrics
          plugin_traffic: yes

          # Display WakaTime stats
          plugin_wakatime: yes
          # WakaTime API token
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          # WakaTime time range
          plugin_wakatime_days: 14 # optional, default is 7
          # Sections to display
          #plugin_wakatime_sections: # optional, default is time, projects, projects-graphs, languages, languages-graphs, editors, os
          # Maximum number of entries to display per graph
          # plugin_wakatime_limit: # optional, default is 5
          # Address where to reach your Wakatime instance
          #plugin_wakatime_url: # optional, default is https://wakatime.com
          # Your Wakatime user on the selfhosted Wakapi instance
          #plugin_wakatime_user: # optional, default is current
