name: Update GitHub Metrics SVG

on:
  schedule: [ { cron: "0 */14 * * *" } ]
  workflow_dispatch:

jobs:
  update-github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Update GitHub Metrics
        uses: lowlighter/metrics@v3.20
        with:
          # Include forks
          repositories_forks: yes # optional, default is <default-value>

          # GitHub Personal Token
          token: ${{ secrets.GH_TOKEN }}

          # GitHub Token used to commit metrics
          committer_token: ${{ secrets.GH_TOKEN }}
          # Branch used to commit rendered metrics
          committer_branch: github-metrics
          # Commit message
          committer_message: "Update `${filename}`"

          # GitHub username
          user: mheob
          # Template to use
          template: classic
          # Metrics base content
          base: header, activity, community, repositories, metadata
          # Render display width
          #config_display: large # optional, default regular
          # Timezone used
          config_timezone: Europe/Berlin

          # Display achievements
          plugin_achievements: yes
          # Display rank minimal threshold
          plugin_achievements_threshold: B # optional, default is C
          # Display unlocked secrets achievements
          #plugin_achievements_secrets: # optional, default is true
          # Achievements display style
          plugin_achievements_display: compact # optional, default is detailed
          # Maximum number of achievements to display
          #plugin_achievements_limit: # optional, default is 0
          # Unlocked achievements to hide
          #plugin_achievements_ignored: # optional, default is
          # Unlocked achievements to display
          #plugin_achievements_only: # optional, default is

          # Display lines of code metrics
          plugin_lines: yes
          # Skipped repositories
          #plugin_lines_skipped: # optional,

          # Display notable contributions in organizations
          plugin_notable: yes
          # Query filter
          plugin_notable_filter: stars:>49 # optional, default is
          # Filter by repository host account type
          plugin_notable_from: all # optional, default is organization
          # Also display repository name
          plugin_notable_repositories: yes # optional
          # Indepth notable contributions processing
          plugin_notable_indepth: yes # optional

          # Display repositories traffic metrics
          plugin_traffic: yes
          # Skipped repositories
          #plugin_traffic_skipped: # optional
