name: Update Daily.dev-Card

on:
  schedule: [ { cron: "23 */13 * * *" } ]
  workflow_dispatch:

jobs:
  devcard:
    name: Update Daily.dev-Card
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Update Daily.dev-Card
        uses: dailydotdev/action-devcard@3.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          user_id: ${{ secrets.DAILYDEV_USER_ID }}
          commit_message: "Update `${filename}`"
          committer_email: "tools@boehm.work"
          committer_name: "Alex Böhm"
