name: Update Daily.dev-Card

on:
  schedule: [ { cron: "23 */13 * * *" } ]
  workflow_dispatch:

jobs:
  devcard:
    name: Update Daily.dev-Card
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Update Daily.dev-Card
        uses: dailydotdev/action-devcard@2.3.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          devcard_id: ${{ secrets.DAILYDEV_CARD_ID }}
          commit_message: "Update `${filename}`"
