name: Update the Daily.dev-Card

on:
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  devcard:
    runs-on: ubuntu-latest

    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.4
        with:
          devcard_id: ${{ secrets.DAILYDEV_CARD_ID }}
          token: ${{ secrets.GH_TOKEN }}
          commit_branch: devcard
          commit_message: "Update `${filename}`"
