name: Update Daily.dev-Card

on:
  schedule: [ { cron: "23 */13 * * *" } ]
  workflow_dispatch:

jobs:
  devcard:
    name: Update Daily.dev-Card
    runs-on: ubuntu-latest

    steps:
      - name: Update Daily.dev-Card
        uses: dailydotdev/action-devcard@2.0.6
        with:
          devcard_id: ${{ secrets.DAILYDEV_CARD_ID }}
          token: ${{ secrets.GH_TOKEN }}
          commit_branch: devcard
          commit_message: "Update `${filename}`"
