name: Update Readme with Wakatime stats

on:
  schedule: [ { cron: "0 */14 * * *" } ]
  workflow_dispatch:

jobs:
  update-waka:
    name: Update Readme with Wakatime stats
    runs-on: ubuntu-latest
    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@master
        with:
          # GitHub access token with Repo scope - default is ${{ github.token }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Your Wakatime API Key
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Show the list of OS Worked on In dev metrics - default is True
          SHOW_OS: False
          # Show the list of projects worked on in dev metrics - default is True
          SHOW_PROJECTS: False
          # Show the Editors used in dev metrics - default is True
          SHOW_EDITORS: False
          # Show the time zone in the dev metrics - default is True
          SHOW_TIMEZONE: False
          # Shows the number of commit graph in the dev metrics - default is True
          SHOW_COMMIT: True
          # Show the Coding language used in dev metrics - default is True
          SHOW_LANGUAGE: True
          # Show the Total Lines of code written Badge till date - default is False
          SHOW_LINES_OF_CODE: False
          # Show language or framework used across different repository - default is True
          SHOW_LANGUAGE_PER_REPO: False
          # Show diagram Lines of code written in different quarters of different year - default is True
          SHOW_LOC_CHART: False
          # Show day of week you are most productive - default is True
          SHOW_DAYS_OF_WEEK: True
          # Show the current profile views - default is True
          SHOW_PROFILE_VIEWS: False
          # Show the short facts - default is True
          SHOW_SHORT_INFO: False
          # Show stats in your own language - default is en
          LOCALE: en
          # Show Total Time you have coded
          SHOW_TOTAL_CODE_TIME: False
          # Git commit with your own name and email
          COMMIT_BY_ME: True
