name: Readme with Metrics

on:
  schedule:
    - cron: '35 02 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    steps:
      - name: Profile Readme Development Stats
        uses: th3c0d3br34ker/github-readme-info@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: "Europe/Berlin"
          SHOW_LINES_OF_CODE: True
          SHOW_PROFILE_VIEWS: True
          SHOW_DAILY_COMMIT: True
          SHOW_WEEKLY_COMMIT: True
          SHOW_LANGUAGE: True
          SHOW_TOTAL_CONTRIBUTIONS: True
