name: Update Readme with GitHub stats

on:
  schedule:
    - cron: "38 01 * * *"
  workflow_dispatch:

jobs:
  update-github:
    name: Update Readme with GitHub stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name mheob
            git config user.email 3983539+mheob@users.noreply.github.com
            git add .
            git commit -m "Update README"
            git push
          fi
