name: Readme with Metrics

on:
  schedule:
    - cron: '35 02 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: False
          SHOW_PROJECTS: True
          SHOW_EDITORS: False
          SHOW_TIMEZONE: False
          SHOW_COMMIT: True
          SHOW_LANGUAGE: True
          SHOW_LINES_OF_CODE: True
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_LOC_CHART: False
          SHOW_DAYS_OF_WEEK: True
          SHOW_PROFILE_VIEWS: True
          SHOW_SHORT_INFO: False
          LOCALE: en
