name: Update Readme with Wakatime stats

on:
  schedule: [{ cron: '51 */13 * * *' }]
  workflow_dispatch:

jobs:
  update-waka:
    name: Update Readme with Wakatime stats
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # optional if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          REPOSITORY: mheob/mheob # optional
          ### content
          SHOW_TITLE: true # optional
          # SECTION_NAME: waka # optional
          BLOCKS: -> # optional
          CODE_LANG: ts # optional
          TIME_RANGE: last_14_days # optional
          # LANG_COUNT: 10 # optional
          # SHOW_TIME: true # optional
          # SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: true # optional
          # STOP_AT_OTHER: true # optional
          # IGNORED_LANGUAGES: YAML JSON TOML # optional
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: main # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: Alex Böhm # optional
          COMMITTER_EMAIL: tools@boehm.work # optional
          AUTHOR_NAME: Alex Böhm # optional
          AUTHOR_EMAIL: tools@boehm.work # optional
          # you can populate email-id with secrets instead
